"""Curriculum data for Project 1: Build an LLM Playground."""

PROJECT_1 = {
    "number": 1,
    "title": "Build an LLM Playground",
    "description": "Build an LLM Playground",
    "topics": [
        {
            "title": "Pre-Training",
            "content": (
                "## Pre-Training\n\n"
                "Pre-training is the foundational stage in building a large language model (LLM). "
                "During this phase, the model learns the statistical structure of language by "
                "processing massive amounts of raw, unlabeled text from the internet, books, and "
                "other sources. The objective is typically **next-token prediction** (causal language "
                "modeling): given a sequence of tokens, predict the next one.\n\n"
                "### The Three Stages of LLM Development\n\n"
                "1. **Pre-training** — The model learns general language understanding from trillions "
                "of tokens. This is the most compute-intensive stage, often requiring thousands of "
                "GPUs running for weeks or months.\n"
                "2. **Post-training** — The base model is refined through supervised fine-tuning (SFT) "
                "and reinforcement learning from human feedback (RLHF) to follow instructions and "
                "align with human preferences.\n"
                "3. **Evaluation** — The model is assessed using automated benchmarks, human "
                "evaluation, and task-specific metrics to measure quality, safety, and capability.\n\n"
                "### Why Pre-Training Matters\n\n"
                "Pre-training gives the model its **world knowledge** and **reasoning abilities**. "
                "Without a strong pre-trained foundation, no amount of fine-tuning can compensate. "
                "Key decisions at this stage include:\n\n"
                "- **Data composition** — What mix of web pages, books, code, and specialized text?\n"
                "- **Model architecture** — Decoder-only (GPT-style) vs. encoder-decoder (T5-style)?\n"
                "- **Scale** — How many parameters and how many tokens to train on?\n"
                "- **Training infrastructure** — Distributed training across GPU/TPU clusters.\n\n"
                "The Chinchilla scaling laws suggest that model size and data size should be scaled "
                "roughly equally for compute-optimal training. Modern models like LLaMA 3 train on "
                "15+ trillion tokens, far exceeding earlier estimates of optimal data requirements."
            ),
            "children": [
                {
                    "title": "Data collection",
                    "content": (
                        "## Data Collection\n\n"
                        "The quality and scale of pre-training data fundamentally determines what an LLM "
                        "can learn. Modern LLMs are trained on **trillions of tokens** sourced from diverse "
                        "origins.\n\n"
                        "### Common Data Sources\n\n"
                        "| Source | Description | Scale |\n"
                        "|--------|-------------|-------|\n"
                        "| Common Crawl | Web scrape of billions of pages | ~250B pages |\n"
                        "| Wikipedia | High-quality encyclopedic text | ~4B words |\n"
                        "| Books (BookCorpus, Gutenberg) | Long-form structured writing | ~1B words |\n"
                        "| GitHub / StackOverflow | Code and technical Q&A | ~100B tokens |\n"
                        "| ArXiv / PubMed | Scientific and medical papers | ~50B tokens |\n"
                        "| Reddit (pushshift) | Conversational text | ~100B tokens |\n\n"
                        "### Key Considerations\n\n"
                        "- **Quality vs. Quantity** — Not all data is equal. A curated 1T-token dataset can "
                        "outperform a noisy 5T-token dataset. Projects like RedPajama and Dolma focus on "
                        "high-quality, open data.\n"
                        "- **Deduplication** — Exact and near-duplicate removal is critical. Duplicated data "
                        "causes the model to memorize rather than generalize. Tools like MinHash and "
                        "SimHash are commonly used.\n"
                        "- **Data mix ratios** — The proportion of web, code, books, and other sources is "
                        "carefully tuned. LLaMA used roughly 67% web, 4.5% GitHub code, 4.5% Wikipedia, "
                        "and the rest from books and academic papers.\n"
                        "- **Licensing and ethics** — Responsible data collection considers copyright, "
                        "consent, and the inclusion of personal information.\n\n"
                        "### Data Pipeline Overview\n\n"
                        "```\n"
                        "Raw Crawl → Language ID → Dedup → Quality Filter → Tokenize → Shuffle → Train\n"
                        "```\n\n"
                        "The entire pipeline is typically orchestrated with tools like Apache Spark or "
                        "Datatrove, processing petabytes of raw text into clean, tokenized training shards."
                    ),
                },
                {
                    "title": "Data cleaning",
                    "content": (
                        "## Data Cleaning\n\n"
                        "Raw internet text is noisy, containing boilerplate HTML, ads, duplicates, toxic "
                        "content, and personally identifiable information (PII). Data cleaning transforms "
                        "this raw text into a high-quality training corpus.\n\n"
                        "### Core Cleaning Steps\n\n"
                        "1. **Text Extraction** — Strip HTML/XML tags, extract main content, remove "
                        "navigation menus and footers using tools like trafilatura or jusText.\n\n"
                        "2. **Text Normalization** — Standardize Unicode, fix encoding issues, normalize "
                        "whitespace, and handle special characters consistently.\n\n"
                        "3. **Language Filtering** — Use fastText or CLD2 classifiers to identify and "
                        "filter documents by language. Most English LLMs filter for English-dominant text "
                        "with a confidence threshold (e.g., >0.65).\n\n"
                        "4. **Quality Filtering** — Remove low-quality documents using heuristics:\n"
                        "   - Documents with too few words or too many special characters\n"
                        "   - Pages with abnormal word-length distributions\n"
                        "   - Classifier-based quality scoring (e.g., trained on Wikipedia vs. random web)\n\n"
                        "5. **PII Removal** — Detect and redact emails, phone numbers, addresses, and "
                        "other personal data using regex patterns and NER models.\n\n"
                        "6. **Toxicity Detection** — Flag or remove content with hate speech, violence, or "
                        "explicit material using classifiers like Perspective API or custom models.\n\n"
                        "7. **Near-Duplicate Removal** — Use MinHash with Locality-Sensitive Hashing (LSH) "
                        "to find and remove near-duplicate documents. This is crucial because even ~1% "
                        "duplication can lead to memorization artifacts.\n\n"
                        "### Impact on Model Quality\n\n"
                        "Research shows that cleaning quality has a **larger effect on downstream "
                        "performance** than simply adding more data. The Phi series of models demonstrated "
                        "that small models trained on carefully curated \"textbook-quality\" data can rival "
                        "much larger models trained on noisier corpora."
                    ),
                },
                {
                    "title": "Tokenization",
                    "content": (
                        "## Tokenization\n\n"
                        "Tokenization converts raw text into a sequence of integer IDs that the model can "
                        "process. The choice of tokenizer affects vocabulary size, sequence length, and "
                        "the model's ability to handle rare words and multilingual text.\n\n"
                        "### Byte-Pair Encoding (BPE) — Step by Step\n\n"
                        "BPE is the most common algorithm used in modern LLMs (GPT, LLaMA):\n\n"
                        "1. Start with a vocabulary of individual characters (or bytes)\n"
                        "2. Count all adjacent token pairs in the training corpus\n"
                        "3. Merge the most frequent pair into a new token\n"
                        "4. Repeat steps 2-3 until the desired vocabulary size is reached\n\n"
                        "Example: `\"low low low lowest\"` → merges `l+o` → `lo`, then `lo+w` → `low`, etc.\n\n"
                        "### Other Algorithms\n\n"
                        "- **WordPiece** (BERT) — Similar to BPE but selects merges that maximize "
                        "likelihood of the training data rather than raw frequency.\n"
                        "- **SentencePiece** (T5, LLaMA) — Language-agnostic; operates on raw Unicode "
                        "without pre-tokenization. Treats the input as a raw byte stream.\n\n"
                        "### Vocabulary Size Tradeoffs\n\n"
                        "| Vocab Size | Pros | Cons |\n"
                        "|------------|------|------|\n"
                        "| Small (~8K) | Compact embedding table | Longer sequences, slower |\n"
                        "| Medium (~32K) | Good balance | Standard choice |\n"
                        "| Large (~100K+) | Shorter sequences | Larger embedding matrix |\n\n"
                        "### Python Example with tiktoken\n\n"
                        "```python\n"
                        "import tiktoken\n\n"
                        "# Use the GPT-4 tokenizer\n"
                        "enc = tiktoken.encoding_for_model(\"gpt-4\")\n\n"
                        "text = \"Hello, world! Tokenization is fascinating.\"\n"
                        "tokens = enc.encode(text)\n"
                        "print(f\"Text: {text}\")\n"
                        "print(f\"Tokens: {tokens}\")\n"
                        "print(f\"Token count: {len(tokens)}\")\n"
                        "print(f\"Decoded: {[enc.decode([t]) for t in tokens]}\")\n"
                        "# Output: ['Hello', ',', ' world', '!', ' Token', 'ization', ' is', ' fascinating', '.']\n"
                        "```\n\n"
                        "Modern models use byte-level BPE to ensure every possible input can be encoded, "
                        "avoiding the dreaded `[UNK]` token entirely."
                    ),
                },
                {
                    "title": "Architecture",
                    "content": (
                        "## Architecture\n\n"
                        "Modern LLMs are built on the **Transformer** architecture, introduced in the "
                        "landmark 2017 paper *\"Attention Is All You Need\"*. The core innovation is the "
                        "**self-attention mechanism**, which lets the model weigh the importance of every "
                        "token relative to every other token in the sequence.\n\n"
                        "### Self-Attention (Q, K, V)\n\n"
                        "Each input token is projected into three vectors:\n"
                        "- **Query (Q)** — What am I looking for?\n"
                        "- **Key (K)** — What do I contain?\n"
                        "- **Value (V)** — What information do I provide?\n\n"
                        "```\n"
                        "Attention(Q, K, V) = softmax(Q @ K^T / sqrt(d_k)) @ V\n"
                        "```\n\n"
                        "### Multi-Head Attention\n\n"
                        "Instead of one attention computation, the model runs `h` parallel attention "
                        "\"heads\", each learning different relationship patterns. Outputs are concatenated "
                        "and projected.\n\n"
                        "### Transformer Block Diagram\n\n"
                        "```mermaid\n"
                        "graph TD\n"
                        "    A[Input Embeddings + Positional Encoding] --> B[Multi-Head Attention]\n"
                        "    M[\"Masked (causal)\"] -.-> B\n"
                        "    B -- \"+ Residual\" --> C[Layer Norm]\n"
                        "    C --> D[\"Feed-Forward (up-project → GELU → down-project)\"]\n"
                        "    D -- \"+ Residual\" --> E[Layer Norm]\n"
                        "    E -- \"repeat N×\" --> F[Linear + Softmax]\n"
                        "    F --> G[Next-token probabilities]\n"
                        "```\n\n"
                        "### Decoder-Only vs. Encoder-Decoder\n\n"
                        "- **Decoder-only** (GPT, LLaMA, Mistral) — Uses causal masking so each token "
                        "only attends to previous tokens. Dominant for text generation.\n"
                        "- **Encoder-decoder** (T5, BART) — Encoder sees full input bidirectionally; "
                        "decoder generates output autoregressively. Better for translation and "
                        "summarization.\n\n"
                        "### Modern Enhancements\n\n"
                        "- **RMSNorm** instead of LayerNorm for stability\n"
                        "- **RoPE** (Rotary Position Embeddings) for length generalization\n"
                        "- **GQA** (Grouped-Query Attention) to reduce KV-cache memory\n"
                        "- **SwiGLU** activation in the FFN layers"
                    ),
                },
                {
                    "title": "Text generation",
                    "content": (
                        "## Text Generation\n\n"
                        "Once a language model is trained, text generation works through **autoregressive "
                        "decoding**: the model predicts one token at a time, appending each prediction to "
                        "the input and repeating until a stop condition is met.\n\n"
                        "### Decoding Strategies\n\n"
                        "- **Greedy decoding** — Always pick the highest-probability token. Fast but "
                        "repetitive and deterministic.\n"
                        "- **Beam search** — Track the top-`b` most probable sequences in parallel. "
                        "Better for translation; can be bland for open-ended generation.\n"
                        "- **Sampling** — Randomly sample from the probability distribution for more "
                        "creative and diverse outputs.\n\n"
                        "### Sampling Parameters\n\n"
                        "- **Temperature (T)** — Scales logits before softmax. `T < 1` sharpens the "
                        "distribution (more deterministic); `T > 1` flattens it (more random).\n"
                        "- **Top-k** — Only sample from the `k` most probable tokens. Eliminates the "
                        "long tail of unlikely tokens.\n"
                        "- **Top-p (nucleus sampling)** — Sample from the smallest set of tokens whose "
                        "cumulative probability ≥ `p`. Adapts the candidate set size dynamically.\n"
                        "- **Repetition penalty** — Reduce the probability of tokens that have already "
                        "appeared, preventing the model from looping.\n\n"
                        "### Python Example\n\n"
                        "```python\n"
                        "import torch\n"
                        "import torch.nn.functional as F\n\n"
                        "def sample_next_token(logits, temperature=0.8, top_k=50, top_p=0.9):\n"
                        "    \"\"\"Sample a token from logits with temperature, top-k, and top-p.\"\"\"\n"
                        "    logits = logits / temperature\n\n"
                        "    # Top-k filtering\n"
                        "    if top_k > 0:\n"
                        "        top_k_vals, _ = torch.topk(logits, top_k)\n"
                        "        logits[logits < top_k_vals[..., -1:]] = float('-inf')\n\n"
                        "    # Top-p (nucleus) filtering\n"
                        "    sorted_logits, sorted_idx = torch.sort(logits, descending=True)\n"
                        "    cumulative_probs = torch.cumsum(F.softmax(sorted_logits, dim=-1), dim=-1)\n"
                        "    mask = cumulative_probs - F.softmax(sorted_logits, dim=-1) >= top_p\n"
                        "    sorted_logits[mask] = float('-inf')\n"
                        "    logits = sorted_logits.scatter(-1, sorted_idx.argsort(-1), sorted_logits)\n\n"
                        "    probs = F.softmax(logits, dim=-1)\n"
                        "    return torch.multinomial(probs, num_samples=1)\n"
                        "```\n\n"
                        "In practice, libraries like Hugging Face Transformers handle all of these "
                        "strategies via the `model.generate()` API with simple keyword arguments."
                    ),
                },
            ],
        },
        {
            "title": "Post-Training",
            "content": (
                "## Post-Training\n\n"
                "After pre-training, a base language model can generate fluent text, but it "
                "behaves like an uncontrolled text completer rather than a helpful assistant. It may "
                "generate toxic content, refuse to follow instructions, or produce confident but "
                "incorrect answers. **Post-training** transforms this raw model into an aligned, "
                "instruction-following system.\n\n"
                "### Why Alignment Is Necessary\n\n"
                "A base model trained on internet text has learned to predict the *most likely* next "
                "token — not the *most helpful* or *most safe* one. For example:\n\n"
                "- Asked \"What is 2+2?\", a base model might continue with more math questions "
                "instead of answering.\n"
                "- It has no concept of refusing harmful requests.\n"
                "- It cannot distinguish between a user instruction and context text.\n\n"
                "### The Post-Training Pipeline\n\n"
                "```\n"
                "Base Model → SFT (Supervised Fine-Tuning) → RLHF (Reinforcement Learning from "
                "Human Feedback) → Aligned Model\n"
                "```\n\n"
                "1. **Supervised Fine-Tuning (SFT)** — Train the model on curated (instruction, "
                "response) pairs so it learns the *format* of being helpful: answering questions, "
                "following instructions, and maintaining a conversational tone.\n\n"
                "2. **Reinforcement Learning from Human Feedback (RLHF)** — Train a reward model "
                "from human preference data, then use reinforcement learning (PPO) to optimize the "
                "LLM's outputs against that reward model. This teaches the model *what* good answers "
                "look like beyond format.\n\n"
                "### The Impact of Post-Training\n\n"
                "Post-training is what makes the difference between a base model (like LLaMA-base) "
                "and a chat model (like LLaMA-Chat). Despite using orders of magnitude less compute "
                "than pre-training, it dramatically changes the model's behavior and usability. "
                "Recent trends also include **Direct Preference Optimization (DPO)**, which skips "
                "the reward model entirely and optimizes preferences directly."
            ),
            "children": [
                {
                    "title": "SFT",
                    "content": (
                        "## Supervised Fine-Tuning (SFT)\n\n"
                        "Supervised Fine-Tuning is the first post-training step, where the base model "
                        "is trained on high-quality (instruction, response) pairs to learn to follow "
                        "instructions and generate helpful responses.\n\n"
                        "### Instruction Datasets\n\n"
                        "| Dataset | Source | Size | Method |\n"
                        "|---------|--------|------|--------|\n"
                        "| Alpaca | Stanford | 52K | GPT-generated |\n"
                        "| FLAN Collection | Google | ~15M | Academic NLP tasks |\n"
                        "| ShareGPT | Community | ~90K | Real ChatGPT conversations |\n"
                        "| OpenAssistant | LAION | ~160K | Crowd-sourced multi-turn |\n"
                        "| Dolly | Databricks | 15K | Employee-written |\n\n"
                        "### ChatML Format Example\n\n"
                        "Most modern SFT uses a structured chat format:\n\n"
                        "```\n"
                        "<|im_start|>system\n"
                        "You are a helpful assistant.<|im_end|>\n"
                        "<|im_start|>user\n"
                        "Explain gradient descent in simple terms.<|im_end|>\n"
                        "<|im_start|>assistant\n"
                        "Gradient descent is an optimization algorithm that iteratively adjusts\n"
                        "parameters by moving in the direction of steepest decrease in the loss\n"
                        "function. Think of it like a ball rolling downhill...<|im_end|>\n"
                        "```\n\n"
                        "### Training Process\n\n"
                        "1. **Format** the data into the chat template with special tokens\n"
                        "2. **Mask** the loss so it is only computed on the *assistant's response* "
                        "tokens (not the prompt)\n"
                        "3. **Train** for 1-3 epochs with a low learning rate (typically 1e-5 to 2e-5)\n"
                        "4. **Evaluate** on held-out instruction-following benchmarks\n\n"
                        "### Key Hyperparameters\n\n"
                        "- **Learning rate**: 1e-5 to 2e-5 (lower than pre-training)\n"
                        "- **Batch size**: 64-128 (effective, with gradient accumulation)\n"
                        "- **Epochs**: 1-3 (overfitting is a major risk with small datasets)\n"
                        "- **Sequence length**: 2048-8192 tokens\n"
                        "- **Weight decay**: 0.0-0.1\n\n"
                        "**LoRA** (Low-Rank Adaptation) is commonly used for parameter-efficient SFT, "
                        "updating only ~0.1% of parameters while achieving comparable results to full "
                        "fine-tuning."
                    ),
                },
                {
                    "title": "RL and RLHF",
                    "content": (
                        "## RL and RLHF\n\n"
                        "Reinforcement Learning from Human Feedback (RLHF) is the process of using "
                        "human preferences to further align a language model beyond what SFT achieves. "
                        "It teaches the model *which* responses humans prefer, not just the format of "
                        "a response.\n\n"
                        "### The RLHF Pipeline\n\n"
                        "```mermaid\n"
                        "graph LR\n"
                        "    A[\"Collect Preferences (human)\"] --> B[Train Reward Model]\n"
                        "    B --> C[Optimize LLM with PPO against RM]\n"
                        "    C --> D[\"KL Penalty (vs. SFT)\"]\n"
                        "    D --> A\n"
                        "```\n\n"
                        "### Step-by-Step\n\n"
                        "1. **Preference Collection** — For a given prompt, generate two or more "
                        "responses. Human annotators rank them (response A > response B).\n"
                        "2. **Reward Model (RM)** — Train a model (often the same architecture as the "
                        "LLM) to predict a scalar reward score that matches human preferences.\n"
                        "3. **PPO Optimization** — Use Proximal Policy Optimization to update the LLM "
                        "to maximize the reward model's score, with a KL-divergence penalty to prevent "
                        "the model from drifting too far from the SFT checkpoint.\n\n"
                        "### DPO: A Simpler Alternative\n\n"
                        "**Direct Preference Optimization (DPO)** bypasses the reward model entirely. "
                        "It directly optimizes the LLM on preference pairs using a classification-style "
                        "loss. DPO is simpler, more stable, and increasingly popular.\n\n"
                        "### Constitutional AI (CAI)\n\n"
                        "Anthropic's approach uses a set of written principles (a \"constitution\") to "
                        "guide self-critique. The model generates responses, critiques them against the "
                        "constitution, and revises — generating its own preference data for RLHF.\n\n"
                        "### Key Tradeoffs\n\n"
                        "- **PPO**: More expressive but complex, requires reward model serving\n"
                        "- **DPO**: Simpler, offline, but may underperform PPO on complex tasks\n"
                        "- **CAI**: Reduces human annotation cost but depends on principle quality"
                    ),
                },
            ],
        },
        {
            "title": "Evaluation",
            "content": (
                "## Evaluation\n\n"
                "Evaluating generative language models is one of the hardest problems in NLP. "
                "Unlike classification tasks with clear accuracy metrics, generation quality is "
                "inherently subjective, multi-dimensional, and context-dependent.\n\n"
                "### Why Evaluation Is Hard\n\n"
                "- **Open-ended outputs** — There are many valid responses to a single prompt, "
                "making reference-based metrics unreliable.\n"
                "- **Multi-dimensional quality** — A response can be fluent but incorrect, or "
                "accurate but unhelpful. Quality spans factuality, coherence, helpfulness, safety, "
                "and more.\n"
                "- **Distribution shift** — Models may perform well on benchmarks but poorly on "
                "real-world queries, or vice versa.\n"
                "- **Contamination** — Benchmark data may have leaked into training data, inflating "
                "scores artificially.\n\n"
                "### Evaluation Taxonomy\n\n"
                "```mermaid\n"
                "graph TD\n"
                "    A[Evaluation Methods] --> B[Automated]\n"
                "    A --> C[Human]\n"
                "    B --> D[\"Traditional metrics (perplexity, BLEU, ROUGE)\"]\n"
                "    B --> E[\"Task-specific benchmarks (MMLU, HumanEval)\"]\n"
                "    B --> F[\"LLM-as-judge (GPT-4 scoring)\"]\n"
                "    C --> G[\"Preference ranking (Chatbot Arena)\"]\n"
                "    C --> H[Likert-scale rating]\n"
                "    C --> I[Expert domain evaluation]\n"
                "```\n\n"
                "### Best Practices\n\n"
                "- **Use multiple metrics** — No single metric captures overall quality. Combine "
                "automated benchmarks with human evaluation.\n"
                "- **Report confidence intervals** — Small benchmark differences may not be "
                "statistically significant.\n"
                "- **Test for contamination** — Check whether benchmark examples appear in the "
                "training data.\n"
                "- **Evaluate on your use case** — Generic benchmarks may not reflect performance "
                "on your specific application.\n\n"
                "The field is moving toward **LLM-as-judge** approaches (using GPT-4 or Claude to "
                "evaluate outputs) and **live human evaluation** platforms like Chatbot Arena, which "
                "provide the most reliable signal for conversational AI."
            ),
            "children": [
                {
                    "title": "Traditional metrics",
                    "content": (
                        "## Traditional Metrics\n\n"
                        "Traditional NLP metrics provide automated, reproducible scores for language "
                        "model outputs. While imperfect for open-ended generation, they remain useful "
                        "baselines and are essential for specific tasks.\n\n"
                        "### Perplexity (PPL)\n\n"
                        "Measures how well the model predicts a held-out test set. Lower is better.\n\n"
                        "```\n"
                        "PPL = exp(-1/N * Σ log P(token_i | context))\n"
                        "```\n\n"
                        "- **Use when**: Comparing base model quality before fine-tuning.\n"
                        "- **Limitation**: Does not measure response quality, only prediction confidence.\n\n"
                        "### BLEU (Bilingual Evaluation Understudy)\n\n"
                        "Measures n-gram overlap between generated text and reference text.\n\n"
                        "```\n"
                        "BLEU = BP × exp(Σ wₙ × log pₙ)\n"
                        "where pₙ = matched n-grams / total n-grams\n"
                        "      BP  = brevity penalty for short outputs\n"
                        "```\n\n"
                        "- **Use when**: Machine translation, where references are well-defined.\n"
                        "- **Limitation**: Ignores semantics — \"the cat sat\" and \"a feline rested\" "
                        "score poorly despite similar meaning.\n\n"
                        "### ROUGE (Recall-Oriented Understudy for Gisting Evaluation)\n\n"
                        "Measures recall of n-grams from reference text. Variants include:\n\n"
                        "- **ROUGE-1**: Unigram overlap\n"
                        "- **ROUGE-2**: Bigram overlap\n"
                        "- **ROUGE-L**: Longest common subsequence\n\n"
                        "```\n"
                        "ROUGE-N = (matched n-grams in reference) / (total n-grams in reference)\n"
                        "```\n\n"
                        "- **Use when**: Summarization tasks.\n\n"
                        "### F1 Score (Token-level)\n\n"
                        "Harmonic mean of precision and recall at the token level.\n\n"
                        "```\n"
                        "Precision = matched tokens / generated tokens\n"
                        "Recall    = matched tokens / reference tokens\n"
                        "F1        = 2 × (Precision × Recall) / (Precision + Recall)\n"
                        "```\n\n"
                        "- **Use when**: Extractive QA (e.g., SQuAD).\n\n"
                        "### Summary Table\n\n"
                        "| Metric | Task | Range | Direction |\n"
                        "|--------|------|-------|-----------|\n"
                        "| Perplexity | LM quality | 1 to ∞ | Lower ↓ |\n"
                        "| BLEU | Translation | 0-100 | Higher ↑ |\n"
                        "| ROUGE | Summarization | 0-1 | Higher ↑ |\n"
                        "| F1 | QA | 0-1 | Higher ↑ |"
                    ),
                },
                {
                    "title": "Task-specific benchmarks",
                    "content": (
                        "## Task-Specific Benchmarks\n\n"
                        "Modern LLM evaluation relies heavily on standardized benchmarks that test "
                        "specific capabilities like reasoning, coding, math, and factual knowledge. "
                        "These benchmarks allow apple-to-apple comparisons across models.\n\n"
                        "### Major Benchmarks\n\n"
                        "| Benchmark | Capability | Format | # Examples |\n"
                        "|-----------|-----------|--------|------------|\n"
                        "| MMLU | Knowledge (57 subjects) | Multiple choice | 14,042 |\n"
                        "| HumanEval | Code generation | Python functions | 164 |\n"
                        "| GSM8K | Math reasoning | Grade-school word problems | 8,500 |\n"
                        "| HellaSwag | Commonsense reasoning | Sentence completion | 10,042 |\n"
                        "| TruthfulQA | Truthfulness | Open-ended + MC | 817 |\n"
                        "| ARC | Science reasoning | Multiple choice | 7,787 |\n"
                        "| WinoGrande | Coreference resolution | Fill-in-the-blank | 1,267 |\n"
                        "| MBPP | Code generation | Python tasks | 974 |\n\n"
                        "### Benchmark Details\n\n"
                        "- **MMLU** (Massive Multitask Language Understanding) — Tests knowledge "
                        "across 57 academic subjects from STEM to humanities. Uses few-shot prompting "
                        "with multiple-choice answers. GPT-4 scores ~86%.\n"
                        "- **HumanEval** — Each problem defines a function signature and docstring; "
                        "the model writes the implementation. Evaluated with `pass@k` (does any of k "
                        "samples pass all unit tests?).\n"
                        "- **GSM8K** — Grade-school math problems requiring multi-step arithmetic "
                        "reasoning. Models use chain-of-thought prompting to show work.\n"
                        "- **TruthfulQA** — Tests whether models generate truthful answers rather "
                        "than common misconceptions. Many questions are adversarially designed.\n\n"
                        "### Contamination Concerns\n\n"
                        "A growing problem: benchmark data may leak into training corpora. Signs "
                        "include:\n"
                        "- Suspiciously high scores on older benchmarks\n"
                        "- Performance drops on rephrased versions of the same questions\n"
                        "- Models memorizing exact answer sequences\n\n"
                        "Mitigation strategies include creating **private test sets**, using "
                        "**canary strings** to detect data in training sets, and developing "
                        "**dynamic benchmarks** that regularly refresh questions."
                    ),
                },
                {
                    "title": "Human evaluation",
                    "content": (
                        "## Human Evaluation\n\n"
                        "Human evaluation remains the gold standard for assessing LLM quality, "
                        "especially for open-ended generation where automated metrics fall short. "
                        "It captures nuanced aspects of quality that no automated metric can fully "
                        "measure.\n\n"
                        "### Chatbot Arena & Elo Ratings\n\n"
                        "The **LMSYS Chatbot Arena** is the most widely referenced human evaluation "
                        "platform for LLMs. It works as follows:\n\n"
                        "1. Users submit a prompt to two anonymous models simultaneously\n"
                        "2. Users see both responses side-by-side (\"blind\" comparison)\n"
                        "3. Users vote for the better response (or declare a tie)\n"
                        "4. Votes are aggregated into **Elo ratings** (like chess rankings)\n\n"
                        "As of 2024, the Arena leaderboard has collected over 800,000 human votes "
                        "and is widely regarded as the most reliable ranking of LLM capabilities.\n\n"
                        "### Elo Rating System\n\n"
                        "Borrowed from chess, the Elo system updates ratings after each match:\n\n"
                        "```\n"
                        "Expected score: E_A = 1 / (1 + 10^((R_B - R_A) / 400))\n"
                        "Updated rating: R_A' = R_A + K × (S_A - E_A)\n"
                        "```\n\n"
                        "Where `K` is the update factor and `S_A` is the actual outcome (1 for win, "
                        "0.5 for tie, 0 for loss). A 100-point Elo difference implies the higher-rated "
                        "model wins approximately 64% of the time.\n\n"
                        "### Inter-Annotator Agreement (IAA)\n\n"
                        "Measures how consistently different human evaluators agree:\n\n"
                        "- **Cohen's Kappa (κ)** — Measures agreement between two annotators, corrected "
                        "for chance. κ > 0.6 is considered substantial agreement.\n"
                        "- **Fleiss' Kappa** — Extension for multiple annotators.\n"
                        "- **Krippendorff's Alpha** — Handles missing data and various measurement "
                        "scales.\n\n"
                        "### Preference Ranking Methods\n\n"
                        "- **Pairwise comparison** — \"Which response is better?\" — Simplest and most "
                        "reliable. Used by Chatbot Arena.\n"
                        "- **Likert scale** — Rate each response 1-5 on helpfulness, accuracy, etc. "
                        "More informative but noisier.\n"
                        "- **Best-of-N** — Pick the best among N responses. Scales better than "
                        "pairwise for many models.\n\n"
                        "Human evaluation is expensive and slow, which is why the field increasingly "
                        "uses **LLM-as-judge** (e.g., GPT-4 evaluating outputs) as a proxy that "
                        "correlates ~85% with human preferences."
                    ),
                },
            ],
        },
        {
            "title": "Chatbots' Overall Design",
            "content": (
                "## Chatbots' Overall Design\n\n"
                "Building a production chatbot involves much more than a language model. It "
                "requires a carefully designed system architecture that handles conversation "
                "management, safety, performance, and user experience.\n\n"
                "### System Architecture\n\n"
                "```mermaid\n"
                "graph TD\n"
                "    subgraph Client[\"Client (UI)\"]\n"
                "        C1[Chat UI]\n"
                "        C2[Streaming]\n"
                "        C3[Session Mgmt]\n"
                "    end\n"
                "    subgraph Backend[\"API Gateway / Backend\"]\n"
                "        B1[Safety Filters]\n"
                "        B2[Context Manager]\n"
                "        B3[Rate Limiting]\n"
                "        B4[\"Prompt Builder (System Prompt + Memory + User Message)\"]\n"
                "    end\n"
                "    subgraph LLM[\"LLM Provider\"]\n"
                "        L1[Model Serving]\n"
                "        L2[Token Counting]\n"
                "        L3[Response Streaming]\n"
                "    end\n"
                "    C1 --> B1\n"
                "    C2 --> B2\n"
                "    C3 --> B3\n"
                "    B1 --> B4\n"
                "    B2 --> B4\n"
                "    B4 --> LLM\n"
                "```\n\n"
                "### Key Components\n\n"
                "- **System Prompts** — Define the chatbot's persona, capabilities, and constraints. "
                "A well-crafted system prompt sets tone, boundaries, and response format.\n\n"
                "- **Conversation Management** — Maintain multi-turn context by appending messages "
                "to a conversation history. Handle turn-taking and track conversation state.\n\n"
                "- **Context Windows** — LLMs have finite context (4K-128K+ tokens). Strategies for "
                "managing long conversations include truncation (drop oldest messages), summarization "
                "(compress older turns), and sliding windows.\n\n"
                "- **Streaming** — Send tokens to the client as they are generated via Server-Sent "
                "Events (SSE) or WebSockets. This dramatically improves perceived latency.\n\n"
                "- **Safety Filters** — Multi-layer defense: input filters (block prompt injection "
                "and jailbreaks), output filters (detect toxic or harmful content), and content "
                "moderation APIs.\n\n"
                "- **Memory** — Long-term memory systems that persist information across "
                "conversations. Approaches include vector databases for retrieval (RAG), structured "
                "memory stores, and conversation summarization.\n\n"
                "### Production Considerations\n\n"
                "- **Latency** — Time-to-first-token (TTFT) matters most for UX. Use streaming.\n"
                "- **Cost** — Track token usage. Cache frequent prompts. Use smaller models when "
                "appropriate.\n"
                "- **Reliability** — Implement retries, fallback models, and graceful degradation.\n"
                "- **Observability** — Log all requests, responses, and metadata for debugging "
                "and improvement."
            ),
            "children": [],
        },
    ],
}
